import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Typography,
  Box,
  IconButton,
  Divider,
  Alert,
  AlertTitle,
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';

interface TermsOfServiceDialogProps {
  open: boolean;
  onClose: () => void;
  onAccept?: () => void;
  showAcceptButton?: boolean;
}

export default function TermsOfServiceDialog({
  open,
  onClose,
  onAccept,
  showAcceptButton = false
}: TermsOfServiceDialogProps) {
  const handleAccept = () => {
    if (onAccept) {
      onAccept();
    }
    onClose();
  };

  return (
    <Dialog open={open} onClose={onClose} maxWidth="md" fullWidth>
      <DialogTitle sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        Terms of Service
        <IconButton
          aria-label="close"
          onClick={onClose}
          sx={{ color: 'grey.500' }}
        >
          <CloseIcon />
        </IconButton>
      </DialogTitle>

      <DialogContent dividers>
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
          <Typography variant="body2" color="text.secondary">
            Last Updated: {new Date().toLocaleDateString()}
          </Typography>

          <Alert severity="warning">
            <AlertTitle>Alpha Tech Preview</AlertTitle>
            This is a POC demonstration, not a commercial product.
            Data may be periodically wiped. Do not store sensitive information.
          </Alert>

          <Alert severity="info">
            OwnPlanner uses a single essential authentication cookie (OwnPlanner.Auth) to keep you signed in. No tracking or analytics cookies are set.
          </Alert>

          <Divider />

          {/* Introduction */}
          <Box>
            <Typography variant="h6" gutterBottom>
              1. Acceptance of Terms
            </Typography>
            <Typography variant="body2" color="text.secondary" paragraph>
              By accessing and using OwnPlanner ("the Service"), you accept and agree to be bound by
              these Terms of Service. If you do not agree to these terms, please do not use the Service.
            </Typography>
          </Box>

          {/* Service Description */}
          <Box>
            <Typography variant="h6" gutterBottom>
              2. Service Description
            </Typography>
            <Typography variant="body2" color="text.secondary" paragraph>
              OwnPlanner is an AI-powered personal planning assistant that helps you manage tasks,
              notes, and stay organized through intelligent conversation. The Service uses Google
              Gemini AI to provide chat-based assistance.
            </Typography>
          </Box>

          {/* AI Service Usage */}
          <Box>
            <Typography variant="h6" gutterBottom>
              3. AI Service and Data Processing
            </Typography>
            <Typography variant="body2" color="text.secondary" paragraph>
              <strong>Important:</strong> OwnPlanner uses Google Gemini AI to power its chat assistant.
              When you interact with the chat feature:
            </Typography>
            <Typography variant="body2" color="text.secondary" component="div">
              <ul style={{ marginTop: 0, paddingLeft: 20 }}>
                <li>Your messages and conversations are sent to Google's AI services for processing</li>
                <li>Google may process and store your data according to their privacy policies</li>
                <li>The AI responses are generated by Google Gemini and may not always be accurate</li>
                <li>You should not share sensitive personal information in conversations</li>
              </ul>
            </Typography>
            <Typography variant="body2" color="text.secondary" paragraph>
              By using the chat feature, you acknowledge and consent to your data being processed by
              Google's AI services as described in Google's privacy policy.
            </Typography>
          </Box>

          {/* User Responsibilities */}
          <Box>
            <Typography variant="h6" gutterBottom>
              4. User Responsibilities
            </Typography>
            <Typography variant="body2" color="text.secondary" component="div">
              You agree to:
              <ul style={{ marginTop: 8, paddingLeft: 20 }}>
                <li>Provide accurate registration information</li>
                <li>Maintain the security of your account credentials</li>
                <li>Use the Service in compliance with applicable laws</li>
                <li>Not use the Service for illegal or unauthorized purposes</li>
                <li>Not attempt to interfere with or disrupt the Service</li>
              </ul>
            </Typography>
          </Box>

          {/* Data and Privacy */}
          <Box>
            <Typography variant="h6" gutterBottom>
              5. Data and Privacy
            </Typography>
            <Typography variant="body2" color="text.secondary" paragraph>
              We collect and store your account information (email, username) and the tasks/notes you
              create. Your chat conversations are processed by Google Gemini AI. We implement reasonable
              security measures to protect your data, but cannot guarantee absolute security.
            </Typography>
          </Box>

          {/* Disclaimer */}
          <Box>
            <Typography variant="h6" gutterBottom>
              6. Disclaimer of Warranties
            </Typography>
            <Typography variant="body2" color="text.secondary" paragraph>
              The Service is provided "AS IS" without warranties of any kind. We do not guarantee that:
            </Typography>
            <Typography variant="body2" color="text.secondary" component="div">
              <ul style={{ marginTop: 0, paddingLeft: 20 }}>
                <li>The Service will be uninterrupted or error-free</li>
                <li>AI-generated responses will be accurate or reliable</li>
                <li>Your data will be completely secure from unauthorized access</li>
                <li>The Service will meet all your requirements</li>
              </ul>
            </Typography>
          </Box>

          {/* Limitation of Liability */}
          <Box>
            <Typography variant="h6" gutterBottom>
              7. Limitation of Liability
            </Typography>
            <Typography variant="body2" color="text.secondary" paragraph>
              To the fullest extent permitted by law, OwnPlanner and its creators shall not be liable
              for any indirect, incidental, special, consequential, or punitive damages resulting from
              your use of the Service, including but not limited to data loss, inaccurate AI responses,
              or unauthorized access to your account.
            </Typography>
          </Box>

          {/* Account Termination */}
          <Box>
            <Typography variant="h6" gutterBottom>
              8. Account Termination
            </Typography>
            <Typography variant="body2" color="text.secondary" paragraph>
              We reserve the right to suspend or terminate your account at any time for violation of
              these terms or for any other reason. You may delete your account at any time by contacting us.
            </Typography>
          </Box>

          {/* Changes to Terms */}
          <Box>
            <Typography variant="h6" gutterBottom>
              9. Changes to Terms
            </Typography>
            <Typography variant="body2" color="text.secondary" paragraph>
              We may modify these Terms of Service at any time. Continued use of the Service after
              changes constitutes acceptance of the modified terms.
            </Typography>
          </Box>

          {/* Open Source */}
          <Box>
            <Typography variant="h6" gutterBottom>
              10. Open Source
            </Typography>
            <Typography variant="body2" color="text.secondary" paragraph>
              OwnPlanner is an open-source project. The source code is available at{' '}
              <a
                href="https://github.com/am-space/own-planner"
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: 'inherit' }}
              >
                https://github.com/am-space/own-planner
              </a>
            </Typography>
          </Box>

          {/* Contact */}
          <Box>
            <Typography variant="h6" gutterBottom>
              11. Contact
            </Typography>
            <Typography variant="body2" color="text.secondary" paragraph>
              For questions about these Terms of Service, please visit our GitHub repository.
            </Typography>
          </Box>

          <Divider />

          <Typography variant="caption" color="text.secondary" align="center">
            By using OwnPlanner, you acknowledge that you have read, understood, and agree to be
            bound by these Terms of Service.
          </Typography>
        </Box>
      </DialogContent>

      <DialogActions>
        {showAcceptButton ? (
          <>
            <Button onClick={onClose} color="inherit">
              Decline
            </Button>
            <Button onClick={handleAccept} color="primary" variant="contained">
              Accept Terms
            </Button>
          </>
        ) : (
          <Button onClick={onClose} color="primary" variant="contained">
            Close
          </Button>
        )}
      </DialogActions>
    </Dialog>
  );
}
